fix: Fcitx5Qt6DBusAddonsConfig dependency & include file name is erro
deepin-community/fcitx5-qt pull request #2
Opened 2023-08-07 02:31 UTC by dengbo11

Fcitx5Qt6DBusAddonsConfig dependency & include file name is erro

Log:

2023-08-07 07:07 UTC, UTsweetyfish requested changes
1. You should use quilt to patch source instead of directly edit the source code.
2. and use `dch` to update debian/changelog.

2023-08-07 09:27 UTC, UTsweetyfish requested changes
debian/patches/series 文件应为 patch 文件名

2023-08-07 09:27 UTC, UTsweetyfish commented on 0001-fix-Fcitx5Qt6DBusAddonsConfig-dependency-include-fil.patch
> +From 07edb501d7be04760d04d4af479d9dbf305cd5ec Mon Sep 17 00:00:00 2001
patch should be placed in debian/patches

2023-08-07 09:27 UTC, UTsweetyfish commented on debian/changelog
> +fcitx5-qt (5.0.16-1deepin) unstable; urgency=medium
```suggestion
fcitx5-qt (5.0.16-0deepin1) unstable; urgency=medium
```

2023-08-07 09:27 UTC, UTsweetyfish commented on qt6/dbusaddons/Fcitx5Qt6DBusAddonsConfig.cmake.in
> +include("${CMAKE_CURRENT_LIST_DIR}/Fcitx5Qt6DBusAddonsTargets.cmake")
这个文件不应该有修改

2023-08-07 09:28 UTC, UTsweetyfish commented
https://www.debian.org/doc/manuals/maint-guide/modify.en.html
https://www.debian.org/doc/manuals/debmake-doc/ch03.en.html#quilt-setup

2023-08-07 09:28 UTC, UTsweetyfish commented
https://www.debian.org/doc/manuals/maint-guide/modify.en.html
https://www.debian.org/doc/manuals/debmake-doc/ch03.en.html#quilt-setup

2023-08-07 09:29 UTC, UTsweetyfish commented on debian/changelog
> +fcitx5-qt (5.0.16-1deepin) unstable; urgency=medium
https://wiki.deepin.org/zh/03_技术规范/03_其他规范/deepin-community分支与Tag管理

2023-09-01 05:30 UTC, Zeno-sole commented
project(fcitx5-qt VERSION 5.0.17)

2023-09-01 05:40 UTC, Zeno-sole commented
/lgtm

2023-09-01 06:04 UTC, UTsweetyfish reviewed
```
$ tardiff fcitx5-qt_5.1.0.orig.tar.xz fcitx5-qt_5.1.0.repack.tar.xz 
+ LICENSES
+ cmake
+ common
+ po
+ qt4
+ qt4/dbusaddons
+ qt4/dbusaddons/interfaces
- qt4/immodule-probing/CMakeLists.txt
- qt4/immodule-probing/main.cpp
+ qt4/inputcontext
+ qt5
+ qt5/dbusaddons
+ qt5/dbusaddons/interfaces
+ qt5/guiwrapper
- qt5/immodule-probing/CMakeLists.txt
- qt5/immodule-probing/main.cpp
+ qt5/platforminputcontext
- qt5/platforminputcontext/fcitx4inputcontextproxy.cpp
- qt5/platforminputcontext/fcitx4inputcontextproxy.h
- qt5/platforminputcontext/fcitx4inputcontextproxy_p.h
- qt5/platforminputcontext/fcitx4inputcontextproxyimpl.cpp
- qt5/platforminputcontext/fcitx4inputcontextproxyimpl.h
- qt5/platforminputcontext/fcitx4inputmethodproxy.cpp
- qt5/platforminputcontext/fcitx4inputmethodproxy.h
- qt5/platforminputcontext/fcitx4watcher.cpp
- qt5/platforminputcontext/fcitx4watcher.h
- qt5/platforminputcontext/hybridinputcontext.cpp
- qt5/platforminputcontext/hybridinputcontext.h
+ qt5/quickphrase-editor
+ qt5/widgetsaddons
+ qt6
+ qt6/dbusaddons
- qt6/immodule-probing/CMakeLists.txt
- qt6/immodule-probing/main.cpp
+ qt6/platforminputcontext
- qt6/platforminputcontext/fcitx4inputcontextproxy.cpp
- qt6/platforminputcontext/fcitx4inputcontextproxy.h
- qt6/platforminputcontext/fcitx4inputcontextproxy_p.h
- qt6/platforminputcontext/fcitx4inputcontextproxyimpl.cpp
- qt6/platforminputcontext/fcitx4inputcontextproxyimpl.h
- qt6/platforminputcontext/fcitx4inputmethodproxy.cpp
- qt6/platforminputcontext/fcitx4inputmethodproxy.h
- qt6/platforminputcontext/fcitx4watcher.cpp
- qt6/platforminputcontext/fcitx4watcher.h
- qt6/platforminputcontext/hybridinputcontext.cpp
- qt6/platforminputcontext/hybridinputcontext.h
+ test
```

这个 git 仓库是从 git 拿的吗？

2023-09-01 06:04 UTC, UTsweetyfish commented
```diff
$ dpkg-source --commit 
dpkg-source: warning: ignoring deletion of symlink qt6/platforminputcontext/fcitx4inputcontextproxy.h
dpkg-source: warning: ignoring deletion of symlink qt6/platforminputcontext/fcitx4inputmethodproxy.h
dpkg-source: warning: ignoring deletion of symlink qt6/platforminputcontext/fcitx4inputcontextproxy_p.h
dpkg-source: warning: ignoring deletion of symlink qt6/platforminputcontext/fcitx4inputcontextproxyimpl.h
dpkg-source: warning: ignoring deletion of symlink qt6/platforminputcontext/fcitx4inputcontextproxyimpl.cpp
dpkg-source: warning: ignoring deletion of symlink qt6/platforminputcontext/fcitx4inputmethodproxy.cpp
dpkg-source: warning: ignoring deletion of symlink qt6/platforminputcontext/hybridinputcontext.h
dpkg-source: warning: ignoring deletion of symlink qt6/platforminputcontext/hybridinputcontext.cpp
dpkg-source: warning: ignoring deletion of symlink qt6/platforminputcontext/fcitx4inputcontextproxy.cpp
dpkg-source: warning: ignoring deletion of symlink qt6/platforminputcontext/fcitx4watcher.h
dpkg-source: warning: ignoring deletion of symlink qt6/platforminputcontext/fcitx4watcher.cpp
dpkg-source: warning: ignoring deletion of directory qt6/immodule-probing
dpkg-source: warning: ignoring deletion of file qt6/immodule-probing/main.cpp, use --include-removal to override
dpkg-source: warning: ignoring deletion of file qt6/immodule-probing/CMakeLists.txt, use --include-removal to override
dpkg-source: warning: ignoring deletion of file qt5/platforminputcontext/fcitx4inputcontextproxy.h, use --include-removal to override
dpkg-source: warning: ignoring deletion of file qt5/platforminputcontext/fcitx4inputmethodproxy.h, use --include-removal to override
dpkg-source: warning: ignoring deletion of file qt5/platforminputcontext/fcitx4inputcontextproxy_p.h, use --include-removal to override
dpkg-source: warning: ignoring deletion of file qt5/platforminputcontext/fcitx4inputcontextproxyimpl.h, use --include-removal to override
dpkg-source: warning: ignoring deletion of file qt5/platforminputcontext/fcitx4inputcontextproxyimpl.cpp, use --include-removal to override
dpkg-source: warning: ignoring deletion of file qt5/platforminputcontext/fcitx4inputmethodproxy.cpp, use --include-removal to override
dpkg-source: warning: ignoring deletion of file qt5/platforminputcontext/hybridinputcontext.h, use --include-removal to override
dpkg-source: warning: ignoring deletion of file qt5/platforminputcontext/hybridinputcontext.cpp, use --include-removal to override
dpkg-source: warning: ignoring deletion of file qt5/platforminputcontext/fcitx4inputcontextproxy.cpp, use --include-removal to override
dpkg-source: warning: ignoring deletion of file qt5/platforminputcontext/fcitx4watcher.h, use --include-removal to override
dpkg-source: warning: ignoring deletion of file qt5/platforminputcontext/fcitx4watcher.cpp, use --include-removal to override
dpkg-source: warning: ignoring deletion of directory qt5/immodule-probing
dpkg-source: warning: ignoring deletion of file qt5/immodule-probing/main.cpp, use --include-removal to override
dpkg-source: warning: ignoring deletion of file qt5/immodule-probing/CMakeLists.txt, use --include-removal to override
dpkg-source: warning: ignoring deletion of directory qt4/immodule-probing
dpkg-source: warning: ignoring deletion of file qt4/immodule-probing/main.cpp, use --include-removal to override
dpkg-source: warning: ignoring deletion of file qt4/immodule-probing/CMakeLists.txt, use --include-removal to override
dpkg-source: warning: file fcitx5-qt/qt4/CMakeLists.txt has no final newline (either original or modified version)
```

2023-09-01 06:22 UTC, UTsweetyfish requested changes
和 github fcitx/fcitx5-qt 里 5.1.0 的版本也对不上啊

2023-09-01 06:47 UTC, UTsweetyfish commented
```diff
diff -Nru fcitx5-qt-git/qt4/CMakeLists.txt fcitx5-qt-dengbo/qt4/CMakeLists.txt
--- fcitx5-qt-git/qt4/CMakeLists.txt	2023-08-15 02:09:49.000000000 +0800
+++ fcitx5-qt-dengbo/qt4/CMakeLists.txt	2023-09-01 13:43:48.657462111 +0800
@@ -1,6 +1,2 @@
 add_subdirectory(dbusaddons)
-add_subdirectory(inputcontext)
-
-if(NOT BUILD_ONLY_PLUGIN)
-  add_subdirectory(immodule-probing)
-endif()
+add_subdirectory(inputcontext)
\ 文件尾没有换行符
diff -Nru fcitx5-qt-git/qt4/immodule-probing/CMakeLists.txt fcitx5-qt-dengbo/qt4/immodule-probing/CMakeLists.txt
--- fcitx5-qt-git/qt4/immodule-probing/CMakeLists.txt	2023-08-15 02:09:49.000000000 +0800
+++ fcitx5-qt-dengbo/qt4/immodule-probing/CMakeLists.txt	1970-01-01 08:00:00.000000000 +0800
@@ -1,4 +0,0 @@
-add_executable(fcitx5-qt4-immodule-probing main.cpp)
-target_link_libraries(fcitx5-qt4-immodule-probing Qt4::QtGui)
-
-install(TARGETS fcitx5-qt4-immodule-probing DESTINATION "${CMAKE_INSTALL_BINDIR}")
\ 文件尾没有换行符
diff -Nru fcitx5-qt-git/qt4/immodule-probing/main.cpp fcitx5-qt-dengbo/qt4/immodule-probing/main.cpp
--- fcitx5-qt-git/qt4/immodule-probing/main.cpp	2023-08-15 02:09:49.000000000 +0800
+++ fcitx5-qt-dengbo/qt4/immodule-probing/main.cpp	1970-01-01 08:00:00.000000000 +0800
@@ -1,20 +0,0 @@
-/*
- * SPDX-FileCopyrightText: 2023~2023 CSSlayer <wengxt@gmail.com>
- *
- * SPDX-License-Identifier: LGPL-2.1-or-later
- *
- */
-#include <QApplication>
-#include <QInputContext>
-#include <iostream>
-
-int main(int argc, char *argv[]) {
-    QApplication app(argc, argv);
-    auto *inputContext = app.inputContext();
-    std::cout << "QT_IM_MODULE=";
-    if (inputContext) {
-        std::cout << inputContext->identifierName().toUtf8().constData();
-    }
-    std::cout << std::endl;
-    return 0;
-}
diff -Nru fcitx5-qt-git/qt5/CMakeLists.txt fcitx5-qt-dengbo/qt5/CMakeLists.txt
--- fcitx5-qt-git/qt5/CMakeLists.txt	2023-08-15 02:09:49.000000000 +0800
+++ fcitx5-qt-dengbo/qt5/CMakeLists.txt	2023-09-01 13:43:26.396638425 +0800
@@ -5,5 +5,4 @@
   add_subdirectory(guiwrapper)
   add_subdirectory(widgetsaddons)
   add_subdirectory(quickphrase-editor)
-  add_subdirectory(immodule-probing)
 endif()
diff -Nru fcitx5-qt-git/qt5/immodule-probing/CMakeLists.txt fcitx5-qt-dengbo/qt5/immodule-probing/CMakeLists.txt
--- fcitx5-qt-git/qt5/immodule-probing/CMakeLists.txt	2023-08-15 02:09:49.000000000 +0800
+++ fcitx5-qt-dengbo/qt5/immodule-probing/CMakeLists.txt	1970-01-01 08:00:00.000000000 +0800
@@ -1,5 +0,0 @@
-add_executable(fcitx5-qt5-immodule-probing main.cpp)
-target_include_directories(fcitx5-qt5-immodule-probing PRIVATE ${Qt5Gui_PRIVATE_INCLUDE_DIRS})
-target_link_libraries(fcitx5-qt5-immodule-probing Qt5::Gui)
-
-install(TARGETS fcitx5-qt5-immodule-probing DESTINATION "${CMAKE_INSTALL_BINDIR}")
\ 文件尾没有换行符
diff -Nru fcitx5-qt-git/qt5/immodule-probing/main.cpp fcitx5-qt-dengbo/qt5/immodule-probing/main.cpp
--- fcitx5-qt-git/qt5/immodule-probing/main.cpp	2023-08-15 02:09:49.000000000 +0800
+++ fcitx5-qt-dengbo/qt5/immodule-probing/main.cpp	1970-01-01 08:00:00.000000000 +0800
@@ -1,29 +0,0 @@
-/*
- * SPDX-FileCopyrightText: 2023~2023 CSSlayer <wengxt@gmail.com>
- *
- * SPDX-License-Identifier: LGPL-2.1-or-later
- *
- */
-#include <QGuiApplication>
-#include <iostream>
-#include <private/qguiapplication_p.h>
-#include <qpa/qplatforminputcontext.h>
-#include <qpa/qplatforminputcontextfactory_p.h>
-#include <qpa/qplatformintegration.h>
-
-int main(int argc, char *argv[]) {
-    QGuiApplication app(argc, argv);
-    std::cout << "QT_QPA_PLATFORM=" << app.platformName().toStdString()
-              << std::endl;
-    std::cout << "QT_IM_MODULE="
-              << QPlatformInputContextFactory::requested().toStdString()
-              << std::endl;
-    auto inputContext =
-        QGuiApplicationPrivate::platformIntegration()->inputContext();
-    std::cout << "IM_MODULE_CLASSNAME=";
-    if (inputContext) {
-        std::cout << inputContext->metaObject()->className();
-    }
-    std::cout << std::endl;
-    return 0;
-}
diff -Nru fcitx5-qt-git/qt6/CMakeLists.txt fcitx5-qt-dengbo/qt6/CMakeLists.txt
--- fcitx5-qt-git/qt6/CMakeLists.txt	2023-08-15 02:09:49.000000000 +0800
+++ fcitx5-qt-dengbo/qt6/CMakeLists.txt	2023-09-01 13:43:26.400638573 +0800
@@ -1,6 +1,2 @@
 add_subdirectory(dbusaddons)
 add_subdirectory(platforminputcontext)
-
-if(NOT BUILD_ONLY_PLUGIN)
-  add_subdirectory(immodule-probing)
-endif()
diff -Nru fcitx5-qt-git/qt6/immodule-probing/CMakeLists.txt fcitx5-qt-dengbo/qt6/immodule-probing/CMakeLists.txt
--- fcitx5-qt-git/qt6/immodule-probing/CMakeLists.txt	2023-08-15 02:09:49.000000000 +0800
+++ fcitx5-qt-dengbo/qt6/immodule-probing/CMakeLists.txt	1970-01-01 08:00:00.000000000 +0800
@@ -1,5 +0,0 @@
-add_executable(fcitx5-qt6-immodule-probing main.cpp)
-target_include_directories(fcitx5-qt6-immodule-probing PRIVATE ${Qt6Gui_PRIVATE_INCLUDE_DIRS})
-target_link_libraries(fcitx5-qt6-immodule-probing Qt6::Gui)
-
-install(TARGETS fcitx5-qt6-immodule-probing DESTINATION "${CMAKE_INSTALL_BINDIR}")
\ 文件尾没有换行符
diff -Nru fcitx5-qt-git/qt6/immodule-probing/main.cpp fcitx5-qt-dengbo/qt6/immodule-probing/main.cpp
--- fcitx5-qt-git/qt6/immodule-probing/main.cpp	2023-08-15 02:09:49.000000000 +0800
+++ fcitx5-qt-dengbo/qt6/immodule-probing/main.cpp	1970-01-01 08:00:00.000000000 +0800
@@ -1,29 +0,0 @@
-/*
- * SPDX-FileCopyrightText: 2023~2023 CSSlayer <wengxt@gmail.com>
- *
- * SPDX-License-Identifier: LGPL-2.1-or-later
- *
- */
-#include <QGuiApplication>
-#include <iostream>
-#include <private/qguiapplication_p.h>
-#include <qpa/qplatforminputcontext.h>
-#include <qpa/qplatforminputcontextfactory_p.h>
-#include <qpa/qplatformintegration.h>
-
-int main(int argc, char *argv[]) {
-    QGuiApplication app(argc, argv);
-    std::cout << "QT_QPA_PLATFORM=" << app.platformName().toStdString()
-              << std::endl;
-    std::cout << "QT_IM_MODULE="
-              << QPlatformInputContextFactory::requested().toStdString()
-              << std::endl;
-    auto inputContext =
-        QGuiApplicationPrivate::platformIntegration()->inputContext();
-    std::cout << "IM_MODULE_CLASSNAME=";
-    if (inputContext) {
-        std::cout << inputContext->metaObject()->className();
-    }
-    std::cout << std::endl;
-    return 0;
-}
diff -Nru fcitx5-qt-git/qt6/platforminputcontext/CMakeLists.txt fcitx5-qt-dengbo/qt6/platforminputcontext/CMakeLists.txt
--- fcitx5-qt-git/qt6/platforminputcontext/CMakeLists.txt	2023-08-15 02:09:49.000000000 +0800
+++ fcitx5-qt-dengbo/qt6/platforminputcontext/CMakeLists.txt	2023-09-01 14:40:10.501197900 +0800
@@ -1,3 +1,5 @@
+include_directories(${Qt6Gui_PRIVATE_INCLUDE_DIRS})
+
 set(FCITX5_QT_EXTRA_PLUGIN_NAME "")
 if (WITH_FCITX_PLUGIN_NAME)
     set(FCITX5_QT_EXTRA_PLUGIN_NAME "\"fcitx\",")
```

2023-09-01 09:14 UTC, UTsweetyfish approved these changes

2023-09-01 09:15 UTC, merged

2023-10-19 07:20 UTC, hudeng-go commented
/integrate